Fixing gaps in autocomplete
scribe-org/Scribe-iOS pull request #195
Opened 2022-08-14 14:04 UTC by SaurabhJamadagni

- PR for part of issue #188 
- Fixed no capitalisation issue and added cases for CapsLock.
- Fixed autocomplete to work even when delete is pressed.
  - This works by having a secondary variable called `secondaryPastStringOnDelete` that stores the previous version of the text in proxy. That way we can return the `pastStringInTextProxy` to the previous line.

@andrewtavis, could you please review these changes. Also could you look into the bug that crashes the keyboard when `delete` is pressed consecutively when the text proxy is empty? I mentioned the exact nature of it in the main issue comments.

2022-08-14 15:11 UTC, andrewtavis requested changes
This is all really good, and I'll definitely use this in the showcase 😊 We'll figure out the delete button press issues later. Long story short, pressing delete has definitely been a problem for various features in the past. What I often need to do is just cancel the actions of the delete button under certain conditions, but then that's not ideal.

Reason for requested changes is that we still need to work a bit on capitalizing the words. If I'm in a language like Spanish and I start typing a with shift at the start, then eventually the autocomplete suggestions will change to lower case - this even though I'm at the start of the proxy. I think that maybe a boolean is needed for this, whereby if shift is pressed, then we're in capitalized mode until such a time as space is pressed or another action that would lower case the words takes place. Let's do some testing in the next week to figure it all out 😊

2022-08-14 15:52 UTC, SaurabhJamadagni commented
> Reason for requested changes is that we still need to work a bit on capitalizing the words. If I'm in a language like Spanish and I start typing a with shift at the start, then eventually the autocomplete suggestions will change to lower case

I see the problem with it @andrewtavis. The words in the JSON are itself lowercased. So even when starting with capitalized letters we are getting lowercased completions. Having a boolean sounds like a good idea. Again a wrong assumption on my part that all words in the JSON would be capitalized. Yes, let's work on it in the coming week :) 

Thanks for the feedback!

2022-08-19 13:58 UTC, SaurabhJamadagni commented
Hi @andrewtavis, I chose against adding one more boolean variable because we still haven't figured out why the keyboard crashes on pressing delete continuously. I extended the String class to capitalize our string correctly. I hope that is okay. Please do review the changes 😊

2022-08-19 16:27 UTC, andrewtavis commented
Sounds great, @SaurabhJamadagni! I'll get to it when I can. I have a mini weekend trip coming up, but I will have some time no doubt 😊

2022-08-19 18:10 UTC, SaurabhJamadagni commented
> I'll get to it when I can. I have a mini weekend trip coming up, but I will have some time no doubt 😊

Yeah absolutely! Have a great trip 😊

2022-08-21 12:32 UTC, andrewtavis commented
I’ll get to the review of this tomorrow odds are, @SaurabhJamadagni :) Just FYI 😊

2022-08-22 11:53 UTC, andrewtavis approved these changes
All looks good on my end, @SaurabhJamadagni :) I'm going to remove the cancelation of the conjugation button for long annotations right now, and then we can work to cut off words and add `...` so they fit only in the translation space later on.

One final change that I'll do here is to make sure that words that are capitalized are only presented as such. So a German noun shouldn't be presented at lower case even if the user is typing in lower case, as odds are it's not the word that they'll select, but it still looks wrong. I'll do this as I think about maybe expanding the autosuggest words, but then in thinking about it it might make sense to simply add the words from the most common list that we'll find in #194 that don't already appear in the list. I think that all nouns + 500 most common words is a solid baseline for this, but then let's not stress about it as we're already making so much progress 😊

Thanks again so much for your work on this!

2022-08-22 11:53 UTC, merged